server:
  port: 8082

spring:
  application:
    name: laizheli-demo
  datasource:
    url: jdbc:mysql://120.55.55.185:3306/teamwork?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: teamwork
    password: 123123123
mybatis-plus:
  configuration: null
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml



