server:
  port: 8088

#spring 配置
spring:
  application:
    name: laizheli-admin
  profiles:
    active: dev  #默认开发环境
  servlet:
    multipart:
      enabled: true  #开启文件上传
      max-file-size: 10MB  #限制文件上传大小为10MB

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
