server:
  port: 8083

#spring 配置
spring:
  application:
    name: laizheli-agent
  profiles:
    active: dev  #默认开发环境
  servlet:
    multipart:
      enabled: true  #开启文件上传
      max-file-size: 10MB  #限制文件上传大小为10MB

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# OSS  阿里云对象存储服务
oos:
  file:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyid: LTAI4GAy8TWyssgboFqMBstR
    keysecret: qBDEQLrLJe09W47IuuTphiKlx5XPDV
    bucketname: laizheli
