server:
  port: 8082

#spring 配置
spring:
  application:
    name: laizheli-client
  profiles:
    active: dev  #默认开发环境
  servlet:
    multipart:
      enabled: true  #开启文件上传
      max-file-size: 10MB  #限制文件上传大小为10MB

  #redis配置
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
